const ALPHABETS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

const sellers = [
  {
    id: 1,
    name: "Wildlife Wonders",
    animals: [
      {
        id: 101,
        name: "Tiger",
        quantity: 2,
        image: "https://example.com/tiger.jpg",
        type: "Wild",
        specie: "Mammal",
      },
      {
        id: 102,
        name: "Parrot",
        quantity: 5,
        image: "https://example.com/parrot.jpg",
        type: "Domestic",
        specie: "Bird",
      },
      {
        id: 103,
        name: "Aquarium",
        quantity: 10,
        image: "https://example.com/aquarium.jpg",
        type: "Domestic",
        specie: "Fish",
      },
    ],
  },
  {
    id: 2,
    name: "Exotic Encounters",
    animals: [
      {
        id: 201,
        name: "Lion",
        quantity: 1,
        image: "https://example.com/lion.jpg",
        type: "Wild",
        specie: "Mammal",
      },
      {
        id: 202,
        name: "Zebra",
        quantity: 3,
        image: "https://example.com/zebra.jpg",
        type: "Wild",
        specie: "Mammal",
      },
      {
        id: 203,
        name: "Monkey",
        quantity: 4,
        image: "https://example.com/monkey.jpg",
        type: "Domestic",
        specie: "Mammal",
      },
    ],
  },
  {
    id: 3,
    name: "Nature's Haven",
    animals: [
      {
        id: 301,
        name: "Hyena",
        quantity: 2,
        image: "https://example.com/hyena.jpg",
        type: "Wild",
        specie: "Mammal",
      },
      {
        id: 302,
        name: "Dogs",
        quantity: 6,
        image: "https://example.com/dogs.jpg",
        type: "Domestic",
        specie: "Mammal",
      },
      {
        id: 303,
        name: "Peacock",
        quantity: 1,
        image: "https://example.com/peacock.jpg",
        type: "Domestic",
        specie: "Bird",
      },
    ],
  },
  {
    id: 4,
    name: "Safari Treasures",
    animals: [
      {
        id: 401,
        name: "Crocodile",
        quantity: 2,
        image: "https://example.com/crocodile.jpg",
        type: "Wild",
        specie: "Reptile",
      },
      {
        id: 402,
        name: "Argentina Horses",
        quantity: 3,
        image: "https://example.com/argentina_horses.jpg",
        type: "Domestic",
        specie: "Mammal",
      },
      {
        id: 403,
        name: "Giraffe",
        quantity: 1,
        image: "https://example.com/giraffe.jpg",
        type: "Wild",
        specie: "Mammal",
      },
    ],
  },
];

export { ALPHABETS, sellers };
