const sellers = [
  {
    id: 1,
    name: "Wildlife Wonders",
    animals: [
      {
        id: 101,
        name: "Tiger",
        quantity: 2,
        image: require("../assets/images/animals/tiger.jpg"),
        type: "Wild",
        specie: "Mammal",
        price: 15000,
      },
      {
        id: 102,
        name: "Parrot",
        quantity: 5,
        image: require("../assets/images/animals/parrot.jpg"),
        type: "Domestic",
        specie: "Bird",
        price: 500,
      },
      {
        id: 103,
        name: "Aquarium",
        quantity: 10,
        image: require("../assets/images/animals/fish.jpg"),
        type: "Domestic",
        specie: "Fish",
        price: 200,
      },
    ],
  },
  {
    id: 2,
    name: "Exotic Encounters",
    animals: [
      {
        id: 201,
        name: "Lion",
        quantity: 1,
        image: require("../assets/images/animals/Lion.jpg"),
        type: "Wild",
        specie: "Mammal",
        price: 20000,
      },
      {
        id: 202,
        name: "Zebra",
        quantity: 3,
        image: require("../assets/images/animals/zebra.jpg"),
        type: "Wild",
        specie: "Mammal",
        price: 7000,
      },
      {
        id: 203,
        name: "Monkey",
        quantity: 4,
        image: require("../assets/images/animals/monkey.jpg"),
        type: "Domestic",
        specie: "Mammal",
        price: 3000,
      },
    ],
  },
  {
    id: 3,
    name: "Nature's Haven",
    animals: [
      {
        id: 301,
        name: "Hyena",
        quantity: 2,
        image: require("../assets/images/animals/hyena.jpg"),
        type: "Wild",
        specie: "Mammal",
        price: 8000,
      },
      {
        id: 302,
        name: "Dogs",
        quantity: 6,
        image: require("../assets/images/animals/dog1.jpg"),
        type: "Domestic",
        specie: "Mammal",
        price: 1000,
      },
      {
        id: 303,
        name: "Peacock",
        quantity: 1,
        image: require("../assets/images/animals/peacock.jpg"),
        type: "Domestic",
        specie: "Bird",
        price: 1500,
      },
    ],
  },
  {
    id: 4,
    name: "Safari Treasures",
    animals: [
      {
        id: 401,
        name: "Crocodile",
        quantity: 2,
        image: require("../assets/images/animals/crocodile.jpg"),
        type: "Wild",
        specie: "Reptile",
        price: 12000,
      },
      {
        id: 402,
        name: "Criollo",
        quantity: 3,
        image: require("../assets/images/animals/criollo.jpg"),
        type: "Domestic",
        specie: "Mammal",
        price: 6000,
      },
      {
        id: 403,
        name: "Giraffe",
        quantity: 1,
        image: require("../assets/images/animals/Giraffe.jpg"),
        type: "Wild",
        specie: "Mammal",
        price: 25000,
      },
    ],
  },
];

export default sellers;
